# Generated by Django 2.2.3 on 2019-08-07 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20190802_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='postcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('투룸', '투룸'), ('고시텔', '고시텔'), ('원룸', '원룸'), ('아파트', '아파트'), ('오피스텔', '오피스텔')], max_length=100),
        ),
    ]
