# Generated by Django 2.2.3 on 2019-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20190807_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('아파트', '아파트'), ('원룸', '원룸'), ('고시텔', '고시텔'), ('오피스텔', '오피스텔'), ('투룸', '투룸')], max_length=100),
        ),
    ]
