# Generated by Django 2.2.3 on 2019-08-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20190807_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sample4_postcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('원룸', '원룸'), ('아파트', '아파트'), ('오피스텔', '오피스텔'), ('고시텔', '고시텔'), ('투룸', '투룸')], max_length=100),
        ),
    ]
