# Generated by Django 2.2.3 on 2019-08-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20190809_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('고시텔', '고시텔'), ('투룸', '투룸'), ('원룸', '원룸'), ('오피스텔', '오피스텔'), ('아파트', '아파트')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='sample4_postcode',
            field=models.IntegerField(null=True),
        ),
    ]
