# Generated by Django 2.2.3 on 2019-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20190809_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('원룸', '원룸'), ('투룸', '투룸'), ('고시텔', '고시텔'), ('아파트', '아파트'), ('오피스텔', '오피스텔')], max_length=100),
        ),
    ]
