# Generated by Django 2.2.3 on 2019-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20190809_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sample5_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('고시텔', '고시텔'), ('아파트', '아파트'), ('오피스텔', '오피스텔'), ('투룸', '투룸'), ('원룸', '원룸')], max_length=100),
        ),
    ]
