# Generated by Django 2.2.3 on 2019-08-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_auto_20190809_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sample4_detailAddress',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sample4_extraAddress',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sample4_jibunAddress',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sample4_postcode',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sample4_roadAddress',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('고시텔', '고시텔'), ('오피스텔', '오피스텔'), ('아파트', '아파트'), ('투룸', '투룸'), ('원룸', '원룸')], max_length=100),
        ),
    ]
