# Generated by Django 2.1.7 on 2019-08-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_auto_20190809_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('원룸', '원룸'), ('아파트', '아파트'), ('고시텔', '고시텔'), ('투룸', '투룸'), ('오피스텔', '오피스텔')], max_length=100),
        ),
    ]
